name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@main

      - name: Set up Go
        uses: actions/setup-go@main
        with:
          go-version: '1.22'

      - name: Check and get dependencies
        run: |
          go mod download

      - name: golangci-lint
        uses: golangci/golangci-lint-action@master